### ISSUE TITLE
Server configuration divided into multiple calls

### ISSUE THREAD

**Issue by Yuyuu** [CodeStory/fluent-http#103]
I was trying to simulate a small web server hosting multiple apps.
At initialization, I wanted each app to be able to add its routes to the server configuration with `server.configure(app.routes());`.

Successive calls to *configure* are possible but from what I can see each call creates a new RoutesProvider (with its own RouteCollection) overriding the previous one.

Would it be relevant to add such a feature ?

**Comment by seblm** [comment]
If you retain current configuration of your web server then you can use `Configuration::overridde`.

For example:
```java
import net.codestory.http.Configuration;
import net.codestory.http.WebServer;

import static net.codestory.http.Configuration.override;

public class MyWebServer {
    private final WebServer server;
    private Configuration currentConfiguration;

    public MyWebServer() {
        currentConfiguration = routes -> routes.get("/", "home");
        server = new WebServer().configure(currentConfiguration);
    }
    
    public void addSomeRoutes(Configuration additionalConfiguration) {
        currentConfiguration = override(currentConfiguration).with(additionalConfiguration);
        server.configure(currentConfiguration);
    }
}
```

**Comment by Yuyuu** [comment]
Alright I completely missed that. Thank you.
