### ISSUE TITLE
Payload error

### ISSUE THREAD

**Issue by mgohin** [CodeStory/fluent-http#104]
When I do something like `return new Payload("text/plain", e.getMessage(), 412);` I got the html error page in the response, any way to avoid this behavior ?

I'm using some resources as REST, so I don't want html pages in responses

**Comment by lauvigne** [comment]
Have you try with the last version?
It's a known problem with version before 2.80 I think

**Comment by seblm** [comment]
Can't reproduce with [this sample](https://github.com/seblm/code-samples/tree/master/web) that uses version 2.91 of fluent-http.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running web.MyWebServerTest
Dev mode. Start with -DPROD_MODE=true to run in production mode.
Server started on port 8080
Reloading configuration...
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.689 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by mgohin** [comment]
We are using 2.79, let's update it ;)
