### ISSUE TITLE
how can I reply an empty error 400 ?

### ISSUE THREAD

**Issue by jpcaruana** [CodeStory/fluent-http#115]
Hi @dgageot , 

I am writing a REST application and I choose to give fluent-http a try.

I will never reply anything but json, this will be a machine to machine service only.

When a client  issues a bad request, I would like to answer with an empty Payload.badRequest() :

````
HTTP/1.1 400 Bad Request
Content-Length: 0
````

Or with a error code / reason (in json) : 

````
HTTP/1.1 400 Bad Request
Content-Type: "application/json"
Content-Length: xxx

{
    "errorCode": 1000,
    "errorLabel": "Some reason human-reading friendly"
}
````

How can I achieve that ? I am a full beginner with fluent-http.
Thanks

**Comment by framiere** [comment]
You can return directly a ```Payload```

```
return new Payload(ContentType.APPLICATION_JSON.toString(), yourJsonObject).withCode(400)
```

**Comment by jpcaruana** [comment]
Thanks, this works fine for empty responses:

````
return new Payload("").withCode(400);
````

my test:
````
@Test
public void productDelete() throws Exception {
    delete("/products/some_id").should()
            .respond(400)
            .beEmpty();
}
````

I didn't find it in the documentation (which is a big file now, difficult to find useful information)

**Comment by dgageot** [comment]
Should you want to change the default behaviour that serves an html page each time there's an error, you could start the server with this code:

~~~
  @Test
  public void suppress_default_error_pages() {
    configure(routes -> routes
        .get("/failure", () -> {
          throw new RuntimeException("BUG");
        })
        .setExtensions(new Extensions() {
          @Override
          public PayloadWriter createPayloadWriter(Request request, Response response, Env env, Site site, Resources resources, CompilerFacade compilers) {
            return new PayloadWriter(request, response, env, site, resources, compilers) {
              @Override
              protected Payload errorPage(Payload payload, Throwable e) {
                return payload;
              }
            };
          }
        })
    );

    get("/not_found").should().respond(404).beEmpty();
    get("/failure").should().respond(500).beEmpty();
  }
~~~

**Comment by jpcaruana** [comment]
thanks, this works like a charm.

Another question : do we have something similar to spring MVC ExceptionHandler ? That would be handy (I haven't read the code yet)

**Comment by jpcaruana** [comment]
this doesn't compile anymore with last (2.96) version. We now have to use: 

````java
 protected Payload errorPage(int errorCode, Throwable e) {
    return new Payload(errorCode);
 }
````
