### ISSUE TITLE
Xml support ???

### ISSUE THREAD

**Issue by trungsi** [CodeStory/fluent-http#122]
It seems that xml support (consume, produce jaxb) is not implemented. if it's the case, is there any plan to implement this feature? Otherwise, can someone shows me an example?

Thanks and regards

**Comment by jeanlaurent** [comment]
Fluent-http is quite young, and mostly focused on fast web app development, that's why we don't have any plan to support jaxb as of now.

What is you use case ?

**Comment by trungsi** [comment]
Do you mean that xml is not for fast web developpment? :). I'm just testing this framework by translating our existing rest app which use xml. It means we'll also need to make code change for client apps.

**Comment by dgageot** [comment]
Sorry we won't implement that.
