### ISSUE TITLE
SSE Stream doesn't seem to close

### ISSUE THREAD

**Issue by stephennt** [CodeStory/fluent-http#129]
I currently have a simple route set up to serve SSE streams. I'd like to detect when the streams are closed so I can unsubscribe from the data provider, but my stream never seems to have onClose called. Any ideas?

public class SSEStream<R,T> {

    private final DataProvider<T> provider;
    private final DataTransformer<R,T> transformer;

    private final static Logger logger = LogManager.getLogger(SSEStream.class);

    public SSEStream(RealtimeHTTPServer server, String servicePath, DataProvider<T> provider, DataTransformer<R,T> transformer) {
        this.provider = provider;
        this.transformer = transformer;
        server.addService(servicePath,this);
    }

    @Get("/subscribe")
    @AllowOrigin("*")
    public Stream<R> subscribe() {
        Queue<R> queue = QueueFactories.<R>unboundedQueue().build();
        DataSubscriber<T> subscriber = new DataSubscriber<T>() {
            @Override
            public void onUpdate(Instant instant, T t) {
                queue.add(transformer.transformTo(instant,t));
            }
        };

        logger.info("Adding SSE subscription for static provider: " + provider.toString());
        provider.addSubscriber(subscriber);

        Stream<R> s = queue.stream();
        return s.onClose(() -> {
            logger.info("Removing SSE subscription for static provider: " + provider.toString());
            provider.removeSubscriber(subscriber);
        });

    }
}

**Comment by dgageot** [comment]
Hi, I couldn't reproduce the bug. Could you build a self contained piece of code that demonstrates the problem?

**Comment by stephennt** [comment]
Please see a test project at https://github.com/stephennt/ReportingServer
If you load the webpage (test.html), after 5 seconds I'd hope to see that my stream gets closed, but I never see this handler called.
