### ISSUE TITLE
Specific js for a single page ?

### ISSUE THREAD

**Issue by jeanlaurent** [CodeStory/fluent-http#63]
Let's say you wan to add a nifty carousel (oh no!) to you web site.
The carousel js code and the js code needed to activate it could be loaded only for a single page (where the carousel is needed) and not on all the pages.

We should maybe think about how to load specific js code for a single page.
Since most of the time we have the js code down at the _layout/default.html code...

**Comment by dgageot** [comment]
I don't get your point. Add a <script> tag on that one page...
