### ISSUE TITLE
Enable CORS for all requests

### ISSUE THREAD

**Issue by mgohin** [CodeStory/fluent-http#77]
I would like to allow CORS (for dev purposes, grunt server etc).
When I do add a ```@AllowOrigin("*")``` on my request method my browser is failing on OPTIONS request : 405 Method not allowed.

There is no doc for cors, only commits and issue #4

**Comment by mgohin** [comment]
I've able to do this for one request :

    .options("/offers", context -> Payload.ok()
                         .withAllowOrigin("*")
                         .withAllowMethods("GET", "POST", "DELETE", "PUT")
                         .withAllowHeaders("Content-Type")
                         .withAllowCredentials(true)
                         .withMaxAge(3600))

but with path "*" it's not working

**Comment by jeanlaurent** [comment]
CORS code has been an external contribution by @cexbrayat and @mathieuancelin.
I've not used it myself.
Would you provide a testcase that produce the error so we have a chance to fix more easly ?

Maybe by adding it there https://github.com/CodeStory/fluent-http/blob/master/src/test/java/net/codestory/http/CORSTest.java ?

**Comment by mgohin** [comment]
In fact it's working for the request ```/offers```, but It seems I can't use regex in path like ```*``` instead of ```/offers```, it's giving me 405 when Chrome is requesting with OPTIONS verb.

Not sure to be able to show you the error via a test because I'm doing cross domain ajax requests with Angular.

**Comment by jeanlaurent** [comment]
Writing a test case is just a way of trying to put the minimal pieces which produce the bug.
Just a better way of describing a bug than plain text, especially since we don't know your exact context.

But I understand simulating cross domain behaviours can be a pain.
Maybe share a *minimal* project showing just the bug then.

**Comment by mgohin** [comment]
I'll try to give you a small project :)

**Comment by code-story** [comment]
Hi. You can't put * instead of /offers. Fluent doesn't support regex as uri
patterns.

Either we implement regex or you can use a filter instead of a route. A bit
more complicated but does the job. The filter would catch all options
request and return the correct Payload

**Comment by mgohin** [comment]
Filter sounds good, any example please ?

**Comment by code-story** [comment]
Take a look at FilterTest
(Sorry no link, I'm in the train)

**Comment by mgohin** [comment]
Nice, works like a charm

    new WebServer().configure(routes -> routes
                .filter((uri, context, nextFilter) -> {
                    if (context.method().equals(Methods.OPTIONS)){
                        return Payload.ok()
                                .withAllowOrigin("*")
                                .withAllowMethods("GET", "POST", "DELETE", "PUT")
                                .withAllowHeaders("Content-Type")
                                .withAllowCredentials(true)
                                .withMaxAge(3600);
                    }
                    return nextFilter.get();
                })
