### ISSUE TITLE
Annotation for authorized roles

### ISSUE THREAD

**Issue by mgohin** [CodeStory/fluent-http#78]
I have this to bind a security on base of a path (here ```/secure```), so any attempt to call ```http://server/secure/offers``` will have to be auth :

    SecurityUsers securityUsers = Provider.singleton(SecurityUsers.class);
    CookieAuthFilter authFilter = new CookieAuthFilter("/secure", securityUsers);

Is there a way to define allowed roles like this :

    @Get("/secure/offers")
    @Roles("ROLE_MODO", "ROLE_ADMIN")
    public List<Offer> getOffers() {
        [...]
    }

It would be great to give easy access

**Comment by dgageot** [comment]
There's no way right now to do that. I'm going to check how we could support custom annotations on resources. That would make it possible to extract Cors annotation handling from mainline and it might make swagger support easier to implement

**Comment by mgohin** [comment]
Lovely, thx !

**Comment by lauvigne** [comment]
This enhancement is very cool! 
I like the allMatch parameter.
Thanks.
