### ISSUE TITLE
Contention on resource under stress

### ISSUE THREAD

**Issue by framiere** [CodeStory/fluent-http#84]
Under heaving concurrent load ```net.codestory.http.templating.helpers.AssetsHelperSource``` should use cache when in ```PROD_MODE```

Here is an jprofiler example when 50 concurrent users are hitting a simple page

![image](https://cloud.githubusercontent.com/assets/505565/6029348/4961fc94-abf0-11e4-8890-0071312fe05c.png)

**Comment by framiere** [comment]
Is this commit https://github.com/CodeStory/fluent-http/commit/289d87638f22c86e89e55d70b485353943d5964e  linked to this issue ? Looks like it.

**Comment by code-story** [comment]
yes!

**Comment by framiere** [comment]
And no HashMap were harmed in the process :) Thanks david.
