### ISSUE TITLE
Can't find HTML pages in 'app' folder when project folder contains accents

### ISSUE THREAD

**Issue by sebprunier** [CodeStory/fluent-http#99]
When the project folder contains accents, the web server does not find resources located in the 'app' directory (dev mode).

Requests such as `localhost:8080/index.html` serve the 404 error page.

I admit that the solution is not to use accents in paths :-)
WDYT ?

**Comment by dgageot** [comment]
On what OS are you?

**Comment by sebprunier** [comment]
I reproduced the issue on Windows 8 and Ubuntu 12.04

**Comment by dgageot** [comment]
This bug is not specific to fluent-http. Java doesn't really like paths with non ascii characters unless you set a correct LC_CTYPE

export LC_CTYPE=UTF-8
